### ISSUE TITLE
Error and the Pic system don't work

### ISSUE THREAD

**Issue by TJFJefroy** [DSH105/HoloAPI#1]
I only get this error [13:15:07] [Server thread/WARN]: [Reflection] Failed retrieve the NMS Player-Object of:JefroyTJF
[13:15:07] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'holo' in plugin HoloAPI v1.0.0
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-1309]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:199) ~[craftbukkit.jar:git-Spigot-1309]
    at org.bukkit.craftbukkit.v1_7_R1.CraftServer.dispatchCommand(CraftServer.java:547) ~[craftbukkit.jar:git-Spigot-1309]
    at net.minecraft.server.v1_7_R1.PlayerConnection.handleCommand(PlayerConnection.java:972) [craftbukkit.jar:git-Spigot-1309]
    at net.minecraft.server.v1_7_R1.PlayerConnection.a(PlayerConnection.java:817) [craftbukkit.jar:git-Spigot-1309]
    at net.minecraft.server.v1_7_R1.PacketPlayInChat.a(PacketPlayInChat.java:28) [craftbukkit.jar:git-Spigot-1309]
    at net.minecraft.server.v1_7_R1.PacketPlayInChat.handle(PacketPlayInChat.java:65) [craftbukkit.jar:git-Spigot-1309]
    at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:147) [craftbukkit.jar:git-Spigot-1309]
    at net.minecraft.server.v1_7_R1.ServerConnection.c(ServerConnection.java:77) [craftbukkit.jar:git-Spigot-1309]
    at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:698) [craftbukkit.jar:git-Spigot-1309]
    at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:273) [craftbukkit.jar:git-Spigot-1309]
    at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:560) [craftbukkit.jar:git-Spigot-1309]
    at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:467) [craftbukkit.jar:git-Spigot-1309]
    at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit.jar:git-Spigot-1309]
Caused by: java.lang.NullPointerException
    at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(Unknown Source) ~[?:1.7.0_51]
    at sun.reflect.UnsafeObjectFieldAccessorImpl.get(Unknown Source) ~[?:1.7.0_51]
    at java.lang.reflect.Field.get(Unknown Source) ~[?:1.7.0_51]
    at com.dsh105.holoapi.util.ReflectionUtil.getField(ReflectionUtil.java:56) ~[?:?]
    at com.dsh105.holoapi.util.PlayerUtil.getPlayerConnection(PlayerUtil.java:32) ~[?:?]
    at com.dsh105.holoapi.util.PlayerUtil.sendPacket(PlayerUtil.java:14) ~[?:?]
    at com.dsh105.holoapi.util.wrapper.protocol.Packet.send(Packet.java:40) ~[?:?]
    at com.dsh105.holoapi.api.Hologram.generate(Hologram.java:252) ~[?:?]
    at com.dsh105.holoapi.api.Hologram.show(Hologram.java:167) ~[?:?]
    at com.dsh105.holoapi.api.Hologram.show(Hologram.java:155) ~[?:?]
    at com.dsh105.holoapi.api.HologramFactory.build(HologramFactory.java:106) ~[?:?]
    at com.dsh105.holoapi.command.HoloCommand.onCommand(HoloCommand.java:114) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-1309]
    ... 13 more

**Comment by TJFJefroy** [comment]
If i use URL than this error heppen [HoloAPI] ••• Loading custom URL image of key %key%...

**Comment by drtshock** [comment]
Your issue was fixed here https://github.com/DSH105/HoloAPI/commit/bea0a6c2d94439f26290bbb1822853bcb7606953

If you have another issue then open a new ticket (:
