### ISSUE TITLE
Holo subcommands fail to register

### ISSUE THREAD

**Issue by Jikoo** [DSH105/HoloAPI#101]
Running HoloAPI #447 with Spigot #1591

On enable, I get the following error which interrupts the registration of subcommands.

```
Error occurred while enabling HoloAPI v2.0.0-SNAPSHOT (Is it up to date?)
com.dsh105.holoapi.libs.command.exception.InvalidCommandException: HoloAPI has attempted to register an invalid command (com.dsh105.holoapi.command.HoloCommand -> debug). Either: Provide a value for "parentCommand" in the annotation, OR add the @Command annotation to the CommandListener class.
        at com.dsh105.holoapi.libs.command.SimpleCommandManager.nestCommandsIn(SimpleCommandManager.java:275) ~[?:?]
        at com.dsh105.holoapi.libs.command.SimpleCommandManager.nestCommandsIn(SimpleCommandManager.java:244) ~[?:?]
        at com.dsh105.holoapi.HoloAPICore.loadCommands(HoloAPICore.java:183) ~[?:?]
        at com.dsh105.holoapi.HoloAPICore.onEnable(HoloAPICore.java:116) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot.jar:git-Spigot-1591]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [spigot.jar:git-Spigot-1591]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-1591]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [spigot.jar:git-Spigot-1591]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [spigot.jar:git-Spigot-1591]
        at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [spigot.jar:git-Spigot-1591]
        at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [spigot.jar:git-Spigot-1591]
        at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [spigot.jar:git-Spigot-1591]
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [spigot.jar:git-Spigot-1591]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot.jar:git-Spigot-1591]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1591]
```

Output of holodebug:

```
[HoloAPI] •••  Debug results:
[HoloAPI] •••  --------------[HoloAPI Stuff]--------------
[HoloAPI] •••  HoloAPI-Version: 2.0.0-SNAPSHOT
[HoloAPI] •••  Message of the day: PressHearthToContinue
[HoloAPI] •••  --------------[CraftBukkit Stuff]--------------
[HoloAPI] •••  Version tag: v1_7_R4
[HoloAPI] •••  NMS-package: net.minecraft.server.v1_7_R4
[HoloAPI] •••  CB-package: org.bukkit.craftbukkit.v1_7_R4
[HoloAPI] •••  Bukkit version: 1.7.10-R0.1-SNAPSHOT
[HoloAPI] •••  --------------[Minecraft Server Stuff]--------------
[HoloAPI] •••  Using Netty: true
[HoloAPI] •••  MinecraftServer: net.minecraft.server.v1_7_R4.MinecraftServer
[HoloAPI] •••  Entity: class net.minecraft.server.v1_7_R4.Entity
[HoloAPI] •••  Is (forge) Modded: Probably not
```

Output of holo: `[HoloAPI] •••  Running HoloAPI v2.0.0-SNAPSHOT. Use /holo help for help.`
Output of holo help: `[HoloAPI] •••  That command does not exist.`

As a byproduct of this, existing holograms aren't loaded and cannot be created using the API with another plugin - this throws a RuntimeException because VaultProvider is null.

**Comment by DSH105** [comment]
https://github.com/DSH105/CommandManager/commit/d315da9bbf7f66603ebb4d995d072f33227bcd32

Should be fixed now :)
