### ISSUE TITLE
NoSuchElementException: packet_handler

### ISSUE THREAD

**Issue by ItsHarry** [DSH105/HoloAPI#118]
HoloAPI version: http://ci.dsh105.com/job/HoloAPI/42/
ProtocolLib version: Latest 1.8-Spigot-patch
Spigot version: 1.8-Patch 20140927a

``` java
[07:29:56] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to HoloAPI v2.0.0-SNAPSHOT
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
    at net.minecraft.server.v1_7_R4.PlayerList.disconnect(PlayerList.java:334) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
    at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:738) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
    at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:77) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
Caused by: java.util.NoSuchElementException: packet_handler
    at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:905) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
    at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:160) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
    at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:153) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
    at com.dsh105.holoapi.protocol.netty.PlayerInjector.inject(PlayerInjector.java:74) ~[?:?]
    at com.dsh105.holoapi.protocol.InjectionManager.inject(InjectionManager.java:125) ~[?:?]
    at com.dsh105.holoapi.protocol.InjectionManager.getInjectorFor(InjectionManager.java:102) ~[?:?]
    at com.dsh105.holoapi.api.HologramImpl.clearTags(HologramImpl.java:613) ~[?:?]
    at com.dsh105.holoapi.api.HologramImpl.clear(HologramImpl.java:580) ~[?:?]
    at com.dsh105.holoapi.listeners.HoloListener.onPlayerQuit(HoloListener.java:68) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor140.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_55]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_55]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-205-g0a049fa]
    ... 11 more
```

**Comment by ItsHarry** [comment]
Any chance on having this fixed? =)

**Comment by CaptainBern** [comment]
@ItsHarry We've had this reported quite a few times. The problem is that with some spigot builds, no errors occur, and with others they do. 

I guess due to changes Spigot made, the network pipeline is also changed but I have no idea what they changed it too and where their version is even located. I'll try to contact some Spigot devs and ask them to help me with this :)

**Comment by ItsHarry** [comment]
Okay thanks
