### ISSUE TITLE
Build 126 console spam

### ISSUE THREAD

**Issue by BriannaThorez** [DSH105/HoloAPI#28]
Citizens latest
Spigot 1300

[23:54:46] [Server thread/INFO]: §5Thiudimir Lut does not exist.
[23:54:46] [Server thread/ERROR]: Could not pass event EntityDamageEvent to HoloAPI v1.1.1-SNAPSHOT
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot1330.jar:git-Spigot-1300]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1330.jar:git-Spigot-1300]
    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30) ~[spigot1330.jar:git-Spigot-1300]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482) [spigot1330.jar:git-Spigot-1300]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:467) [spigot1330.jar:git-Spigot-1300]
    at org.bukkit.craftbukkit.v1_7_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:99) [spigot1330.jar:git-Spigot-1300]
    at org.bukkit.craftbukkit.v1_7_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:403) [spigot1330.jar:git-Spigot-1300]
    at org.bukkit.craftbukkit.v1_7_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:462) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntityLiving.damageEntity(EntityLiving.java:663) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntityMonster.damageEntity(EntityMonster.java:47) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntityLiving.C(EntityLiving.java:162) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntityInsentient.C(EntityInsentient.java:111) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.Entity.h(Entity.java:254) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntityLiving.h(EntityLiving.java:1272) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntityInsentient.h(EntityInsentient.java:150) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntityMonster.h(EntityMonster.java:24) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntitySpider.h(EntitySpider.java:21) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.World.entityJoinedWorld(World.java:1472) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.World.playerJoinedWorld(World.java:1448) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.World.tickEntities(World.java:1317) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.WorldServer.tickEntities(WorldServer.java:514) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:671) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:273) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:560) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:467) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [spigot1330.jar:git-Spigot-1300]
Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
    at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[?:?]
    at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:644) ~[?:?]
    at com.dsh105.holoapi.hook.VaultHook.getRank(VaultHook.java:71) ~[?:?]
    at com.dsh105.holoapi.util.TagFormatter.format(TagFormatter.java:21) ~[?:?]
    at com.dsh105.holoapi.api.Hologram.generate(Hologram.java:444) ~[?:?]
    at com.dsh105.holoapi.api.Hologram.show(Hologram.java:337) ~[?:?]
    at com.dsh105.holoapi.api.Hologram.show(Hologram.java:311) ~[?:?]
    at com.dsh105.holoapi.api.HologramFactory.build(HologramFactory.java:211) ~[?:?]
    at com.dsh105.holoapi.api.SimpleHoloManager.createSimpleHologram(SimpleHoloManager.java:313) ~[?:?]
    at com.dsh105.holoapi.listeners.IndicatorListener.onDamage(IndicatorListener.java:69) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_51]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_51]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:318) ~[spigot1330.jar:git-Spigot-1300]
    ... 25 more
[23:54:46] [Server thread/INFO]: §5Thiudimir Lut does not exist.
[23:54:46] [Server thread/ERROR]: Could not pass event EntityDamageEvent to HoloAPI v1.1.1-SNAPSHOT
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot1330.jar:git-Spigot-1300]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1330.jar:git-Spigot-1300]
    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30) ~[spigot1330.jar:git-Spigot-1300]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482) [spigot1330.jar:git-Spigot-1300]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:467) [spigot1330.jar:git-Spigot-1300]
    at org.bukkit.craftbukkit.v1_7_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:99) [spigot1330.jar:git-Spigot-1300]
    at org.bukkit.craftbukkit.v1_7_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:403) [spigot1330.jar:git-Spigot-1300]
    at org.bukkit.craftbukkit.v1_7_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:462) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntityLiving.damageEntity(EntityLiving.java:663) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntityMonster.damageEntity(EntityMonster.java:47) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntityLiving.C(EntityLiving.java:162) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntityInsentient.C(EntityInsentient.java:111) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.Entity.h(Entity.java:254) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntityLiving.h(EntityLiving.java:1272) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntityInsentient.h(EntityInsentient.java:150) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntityMonster.h(EntityMonster.java:24) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntitySpider.h(EntitySpider.java:21) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.World.entityJoinedWorld(World.java:1472) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.World.playerJoinedWorld(World.java:1448) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.World.tickEntities(World.java:1317) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.WorldServer.tickEntities(WorldServer.java:514) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:671) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:273) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:560) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:467) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [spigot1330.jar:git-Spigot-1300]
Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
    at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[?:?]
    at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:644) ~[?:?]
    at com.dsh105.holoapi.hook.VaultHook.getRank(VaultHook.java:71) ~[?:?]
    at com.dsh105.holoapi.util.TagFormatter.format(TagFormatter.java:21) ~[?:?]
    at com.dsh105.holoapi.api.Hologram.generate(Hologram.java:444) ~[?:?]
    at com.dsh105.holoapi.api.Hologram.show(Hologram.java:337) ~[?:?]
    at com.dsh105.holoapi.api.Hologram.show(Hologram.java:311) ~[?:?]
    at com.dsh105.holoapi.api.HologramFactory.build(HologramFactory.java:211) ~[?:?]
    at com.dsh105.holoapi.api.SimpleHoloManager.createSimpleHologram(SimpleHoloManager.java:313) ~[?:?]
    at com.dsh105.holoapi.listeners.IndicatorListener.onDamage(IndicatorListener.java:69) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_51]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_51]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:318) ~[spigot1330.jar:git-Spigot-1300]
    ... 25 more
[23:54:46] [Server thread/INFO]: §5Thiudimir Lut does not exist.
[23:54:46] [Server thread/ERROR]: Could not pass event EntityDamageEvent to HoloAPI v1.1.1-SNAPSHOT
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot1330.jar:git-Spigot-1300]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1330.jar:git-Spigot-1300]
    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30) ~[spigot1330.jar:git-Spigot-1300]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482) [spigot1330.jar:git-Spigot-1300]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:467) [spigot1330.jar:git-Spigot-1300]
    at org.bukkit.craftbukkit.v1_7_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:99) [spigot1330.jar:git-Spigot-1300]
    at org.bukkit.craftbukkit.v1_7_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:403) [spigot1330.jar:git-Spigot-1300]
    at org.bukkit.craftbukkit.v1_7_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:462) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntityLiving.damageEntity(EntityLiving.java:663) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntityMonster.damageEntity(EntityMonster.java:47) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntityLiving.C(EntityLiving.java:162) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntityInsentient.C(EntityInsentient.java:111) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.Entity.h(Entity.java:254) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntityLiving.h(EntityLiving.java:1272) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntityInsentient.h(EntityInsentient.java:150) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntityMonster.h(EntityMonster.java:24) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.EntitySpider.h(EntitySpider.java:21) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.World.entityJoinedWorld(World.java:1472) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.World.playerJoinedWorld(World.java:1448) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.World.tickEntities(World.java:1317) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.WorldServer.tickEntities(WorldServer.java:514) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:671) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:273) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:560) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:467) [spigot1330.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [spigot1330.jar:git-Spigot-1300]
Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
    at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[?:?]
    at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:644) ~[?:?]
    at com.dsh105.holoapi.hook.VaultHook.getRank(VaultHook.java:71) ~[?:?]
    at com.dsh105.holoapi.util.TagFormatter.format(TagFormatter.java:21) ~[?:?]
    at com.dsh105.holoapi.api.Hologram.generate(Hologram.java:444) ~[?:?]
    at com.dsh105.holoapi.api.Hologram.show(Hologram.java:337) ~[?:?]
    at com.dsh105.holoapi.api.Hologram.show(Hologram.java:311) ~[?:?]
    at com.dsh105.holoapi.api.HologramFactory.build(HologramFactory.java:211) ~[?:?]
    at com.dsh105.holoapi.api.SimpleHoloManager.createSimpleHologram(SimpleHoloManager.java:313) ~[?:?]
    at com.dsh105.holoapi.listeners.IndicatorListener.onDamage(IndicatorListener.java:69) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_51]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_51]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:318) ~[spigot1330.jar:git-Spigot-1300]
    ... 25 more

**Comment by DSH105** [comment]
Thanks for your report. We'll have it fixed soon :)

**Comment by stuntguy3000** [comment]
@tronman2020 Try the newest build from http://ci.hawkfalcon.com/job/HoloAPI/
