### ISSUE TITLE
EventException when joining

### ISSUE THREAD

**Issue by Carlgo11** [DSH105/HoloAPI#53]
I get this error when joining my server (running holoapi v1.2.0 & Spigot build #1416)

```
[15:39:13 ERROR]: Could not pass event PlayerJoinEvent to HoloAPI v1.2.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) ~[spigot.jar:git-Spigot-1416]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1416]
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30) ~[spigot.jar:git-Spigot-1416]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1416]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1416]
        at net.minecraft.server.v1_7_R3.PlayerList.c(PlayerList.java:251) [spigot.jar:git-Spigot-1416]
        at net.minecraft.server.v1_7_R3.PlayerList.a(PlayerList.java:138) [spigot.jar:git-Spigot-1416]
        at net.minecraft.server.v1_7_R3.LoginListener.c(LoginListener.java:105) [spigot.jar:git-Spigot-1416]
        at net.minecraft.server.v1_7_R3.LoginListener.a(LoginListener.java:43) [spigot.jar:git-Spigot-1416]
        at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:170) [spigot.jar:git-Spigot-1416]
        at net.minecraft.server.v1_7_R3.ServerConnection.c(ServerConnection.java:77) [spigot.jar:git-Spigot-1416]
        at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:713) [spigot.jar:git-Spigot-1416]
        at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:283) [spigot.jar:git-Spigot-1416]
        at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:576) [spigot.jar:git-Spigot-1416]
        at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:482) [spigot.jar:git-Spigot-1416]
        at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1416]
Caused by: java.lang.ClassCastException: java.util.concurrent.ConcurrentLinkedQueue cannot be cast to net.minecraft.util.io.netty.channel.Channel
        at com.dsh105.holoapi.protocol.ChannelPipelineInjector.getChannel(ChannelPipelineInjector.java:116) ~[?:?]
        at com.dsh105.holoapi.protocol.ChannelPipelineInjector.<init>(ChannelPipelineInjector.java:47) ~[?:?]
        at com.dsh105.holoapi.protocol.InjectionManager.inject(InjectionManager.java:59) ~[?:?]
        at com.dsh105.holoapi.protocol.InjectionManager$1.onJoin(InjectionManager.java:37) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_51]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_51]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[spigot.jar:git-Spigot-1416]
        ... 15 more
[15:39:13 INFO]: carlgo11[<censored>] logged in with entity id 484 at ([World] -263.00358880626254, 33.3056028972448, 454.2198106821849)
```

**Comment by DSH105** [comment]
Use one of the development builds. We will be uploading a new release soon ;).

**Comment by DSH105** [comment]
https://github.com/DSH105/HoloAPI/commit/26d1b6ab533d8c4e6d05d0f468429b5432b52cf6
