### ISSUE TITLE
java.lang.ClassCastException: com.dsh105.holoapi.protocol.Action cannot be cast to java.lang.Integer

### ISSUE THREAD

**Issue by scholzi100** [DSH105/HoloAPI#62]
[21:08:08 WARN]: [HoloAPI] Task #1450 for HoloAPI v1.2.2-SNAPSHOT generated an exception
java.lang.ClassCastException: com.dsh105.holoapi.protocol.Action cannot be cast to java.lang.Integer
        at com.dsh105.holoapi.protocol.InjectionManager$2.run(InjectionManager.java:164) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:58) ~[spigot.jar:git-Spigot-1443]
        at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345) [spigot.jar:git-Spigot-1443]
        at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:628) [spigot.jar:git-Spigot-1443]
        at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:283) [spigot.jar:git-Spigot-1443]
        at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:576) [spigot.jar:git-Spigot-1443]
        at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:482) [spigot.jar:git-Spigot-1443]
        at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1443]

**Comment by CaptainBern** [comment]
Fixed in: https://github.com/DSH105/HoloAPI/pull/63
