### ISSUE TITLE
[Reflection] Failed to find a matching method

### ISSUE THREAD

**Issue by Shadowgar** [DSH105/HoloAPI#72]
Using Build #343 Removing a hologram or reloading the plugin creates this error:

```
4:09:54 AM CONSOLE: [INFO] ShadowGar issued server command: /holo remove -32767
4:09:58 AM CONSOLE: 
4:09:58 AM CONSOLE: 
4:10:17 AM CONSOLE: [WARNING] [Reflection] Failed to find a matching method with name: h
4:10:17 AM CONSOLE: [SEVERE] java.lang.NoSuchMethodException: net.minecraft.entity.DataWatcher.h(int)
4:10:17 AM CONSOLE: [SEVERE] at java.lang.Class.getDeclaredMethod(Class.java:2004)
4:10:17 AM CONSOLE: [SEVERE] at com.dsh105.holoapi.reflection.SafeMethod.<init>(SafeMethod.java:41)
4:10:17 AM CONSOLE: [SEVERE] at com.dsh105.holoapi.api.Hologram.updateNametag(Hologram.java:873)
4:10:17 AM CONSOLE: [SEVERE] at com.dsh105.holoapi.api.Hologram.updateDisplay(Hologram.java:500)
4:10:17 AM CONSOLE: [SEVERE] at com.dsh105.holoapi.api.Hologram.updateDisplay(Hologram.java:513)
4:10:17 AM CONSOLE: [SEVERE] at com.dsh105.holoapi.api.SimpleHoloManager$UpdateDisplayTask.run(SimpleHoloManager.java:522)
4:10:17 AM CONSOLE: [SEVERE] at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftTask.run(CraftTask.java:58)
4:10:17 AM CONSOLE: [SEVERE] at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
4:10:17 AM CONSOLE: [SEVERE] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:822)
4:10:17 AM CONSOLE: [SEVERE] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
4:10:17 AM CONSOLE: [SEVERE] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
4:10:17 AM CONSOLE: [SEVERE] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
4:10:17 AM CONSOLE: [SEVERE] at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
4:11:17 AM CONSOLE: [WARNING] [Reflection] Failed to find a matching method with name: h
4:11:17 AM CONSOLE: [SEVERE] java.lang.NoSuchMethodException: net.minecraft.entity.DataWatcher.h(int)
4:11:17 AM CONSOLE: [SEVERE] at java.lang.Class.getDeclaredMethod(Class.java:2004)
4:11:17 AM CONSOLE: [SEVERE] at com.dsh105.holoapi.reflection.SafeMethod.<init>(SafeMethod.java:41)
4:11:17 AM CONSOLE: [SEVERE] at com.dsh105.holoapi.api.Hologram.updateNametag(Hologram.java:873)
4:11:17 AM CONSOLE: [SEVERE] at com.dsh105.holoapi.api.Hologram.updateDisplay(Hologram.java:500)
4:11:17 AM CONSOLE: [SEVERE] at com.dsh105.holoapi.api.Hologram.updateDisplay(Hologram.java:513)
4:11:17 AM CONSOLE: [SEVERE] at com.dsh105.holoapi.api.SimpleHoloManager$UpdateDisplayTask.run(SimpleHoloManager.java:522)
4:11:17 AM CONSOLE: [SEVERE] at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftTask.run(CraftTask.java:58)
4:11:17 AM CONSOLE: [SEVERE] at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
4:11:17 AM CONSOLE: [SEVERE] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:822)
4:11:17 AM CONSOLE: [SEVERE] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
4:11:17 AM CONSOLE: [SEVERE] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
4:11:17 AM CONSOLE: [SEVERE] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
4:11:17 AM CONSOLE: [SEVERE] at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
4:11:31 AM CONSOLE: [INFO] ShadowGar issued server command: /holo reload
4:11:31 AM CONSOLE: [WARNING] [Reflection] Failed to find a matching method with name: h
4:11:31 AM CONSOLE: [SEVERE] java.lang.NoSuchMethodException: net.minecraft.entity.DataWatcher.h(int)
4:11:31 AM CONSOLE: [SEVERE] at java.lang.Class.getDeclaredMethod(Class.java:2004)
4:11:31 AM CONSOLE: [SEVERE] at com.dsh105.holoapi.reflection.SafeMethod.<init>(SafeMethod.java:41)
4:11:31 AM CONSOLE: [SEVERE] at com.dsh105.holoapi.api.Hologram.generateFloatingItem(Hologram.java:844)
4:11:31 AM CONSOLE: [SEVERE] at com.dsh105.holoapi.api.Hologram.generate(Hologram.java:748)
4:11:31 AM CONSOLE: [SEVERE] at com.dsh105.holoapi.api.Hologram.show(Hologram.java:626)
4:11:31 AM CONSOLE: [SEVERE] at com.dsh105.holoapi.api.Hologram.show(Hologram.java:595)
4:11:31 AM CONSOLE: [SEVERE] at com.dsh105.holoapi.api.HologramFactory.build(HologramFactory.java:252)
4:11:31 AM CONSOLE: [SEVERE] at com.dsh105.holoapi.api.SimpleHoloManager.loadFileData(SimpleHoloManager.java:298)
4:11:31 AM CONSOLE: [SEVERE] at com.dsh105.holoapi.HoloAPICore.loadHolograms(HoloAPICore.java:236)
4:11:31 AM CONSOLE: [SEVERE] at com.dsh105.holoapi.command.module.ReloadCommand.onCommand(ReloadCommand.java:41)
4:11:31 AM CONSOLE: [SEVERE] at com.dsh105.holoapi.command.CommandModuleManager.onCommand(CommandModuleManager.java:94)
4:11:31 AM CONSOLE: [SEVERE] at com.dsh105.holoapi.command.DynamicPluginCommand.execute(DynamicPluginCommand.java:42)
4:11:31 AM CONSOLE: [SEVERE] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:192)
4:11:31 AM CONSOLE: [SEVERE] at org.bukkit.craftbukkit.v1_6_R3.CraftServer.dispatchCommand(CraftServer.java:533)
4:11:31 AM CONSOLE: [SEVERE] at net.minecraft.network.NetServerHandler.func_72566_d(NetServerHandler.java:1405)
4:11:31 AM CONSOLE: [SEVERE] at net.minecraft.network.NetServerHandler.chat(NetServerHandler.java:1269)
4:11:31 AM CONSOLE: [SEVERE] at net.minecraft.network.NetServerHandler.func_72481_a(NetServerHandler.java:1201)
4:11:31 AM CONSOLE: [SEVERE] at net.minecraft.network.packet.Packet3Chat.func_73279_a(Packet3Chat.java:68)
4:11:31 AM CONSOLE: [SEVERE] at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:470)
4:11:31 AM CONSOLE: [SEVERE] at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:233)
4:11:31 AM CONSOLE: [SEVERE] at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
4:11:31 AM CONSOLE: [SEVERE] at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(DedicatedServerListenThread.java:34)
4:11:31 AM CONSOLE: [SEVERE] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:910)
4:11:31 AM CONSOLE: [SEVERE] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
4:11:31 AM CONSOLE: [SEVERE] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
4:11:31 AM CONSOLE: [SEVERE] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
4:11:31 AM CONSOLE: [SEVERE] at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
4:11:31 AM HoloAPI: Animations loaded.
4:11:36 AM HoloAPI: Holograms loaded

```

**Comment by CaptainBern** [comment]
I'm currently rewriting the reflection framework so errors like these will not occur in the future. I guess you're using MCPC+?

**Comment by Shadowgar** [comment]
Yes, build 251 for 1.6.4

**Comment by DSH105** [comment]
https://github.com/DSH105/HoloAPI/commit/bd5161fac50b14137453d96e53636b488927dd4d
