### ISSUE TITLE
NPE when restarting server / Holos not showing

### ISSUE THREAD

**Issue by recon88** [DSH105/HoloAPI#81]
Using latest Holo and Craftbukkit builds.

```
[17:36:47 WARN]: [HoloAPI] Task #22 for HoloAPI v1.2.3 generated an exception
java.lang.NullPointerException
at java.lang.String.replace(String.java:2228) ~[?:1.7.0_03]
at com.dsh105.holoapi.api.TagFormatter.formatTags(TagFormatter.java:195) ~[?:?]
at com.dsh105.holoapi.api.TagFormatter.format(TagFormatter.java:212) ~[?:?]
at com.dsh105.holoapi.api.Hologram.generate(Hologram.java:737) ~[?:?]
at com.dsh105.holoapi.api.Hologram.show(Hologram.java:618) ~[?:?]
at com.dsh105.holoapi.api.Hologram.show(Hologram.java:587) ~[?:?]
at com.dsh105.holoapi.listeners.HoloListener$1.run(HoloListener.java:84) ~[?:?]
at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit-1.7.9-R0.1-20140514.121948-24.jar:git-Bukkit-1.7.2-R0.3-71-ge1cec47-b3082jnks]
at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345) [craftbukkit-1.7.9-R0.1-20140514.121948-24.jar:git-Bukkit-1.7.2-R0.3-71-ge1cec47-b3082jnks]
at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:600) [craftbukkit-1.7.9-R0.1-20140514.121948-24.jar:git-Bukkit-1.7.2-R0.3-71-ge1cec47-b3082jnks]
at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:260) [craftbukkit-1.7.9-R0.1-20140514.121948-24.jar:git-Bukkit-1.7.2-R0.3-71-ge1cec47-b3082jnks]
at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:558) [craftbukkit-1.7.9-R0.1-20140514.121948-24.jar:git-Bukkit-1.7.2-R0.3-71-ge1cec47-b3082jnks]
at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit-1.7.9-R0.1-20140514.121948-24.jar:git-Bukkit-1.7.2-R0.3-71-ge1cec47-b3082jnks]
at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [craftbukkit-1.7.9-R0.1-20140514.121948-24.jar:git-Bukkit-1.7.2-R0.3-71-ge1cec47-b3082jnks]
```

data.yml

```
holograms:
  '1':
    worldName: world
    x: 280.69999998807907
    y: 82.20000004768372
    z: 191.51200642540894
    lines:
      '0':
        type: text
        value: '&c&lPortal to the'
      '1':
        type: text
        value: '&c&lSurvival world'
```

**Comment by DSH105** [comment]
https://github.com/DSH105/HoloAPI/commit/9741619e0dfe13c54496e4a33a3ca92ca66bf9bb
