### ISSUE TITLE
(BIG BUG) ChatBubbles turning to REAL holograms

### ISSUE THREAD

**Issue by macjuul** [DSH105/HoloAPI#82]
On a server reload/restart or with /holo reload all Chat Bubbles re-appear and turn to Holograms. When you use /holo nearby you can see all chat bubbles are turned to real holograms. I hope this gets fixed soon because this is the best Hologram plugin out there!

**Comment by CaptainBern** [comment]
Thank you for the compliment! Have you tried running the latest (dev) build?

**Comment by macjuul** [comment]
I don't think so. I downloaded the latest version from BukkitDev.

**Comment by macjuul** [comment]
Yes I did. Its version 1.2.3 that has the bug in it. I'm now using the older version becous people really love the chat bubbles.

**Comment by DSH105** [comment]
Try using a dev build :)

**Comment by macjuul** [comment]
Where can I download the dev build?

PS:
Im running CraftBukkit R0.3

**Comment by DSH105** [comment]
http://ci.hawkfalcon.com/job/HoloAPI

**Comment by macjuul** [comment]
Ok thanks Il try it now! ;)

**Comment by DSH105** [comment]
Remember to remove the existing holograms from the data file.

**Comment by macjuul** [comment]
Another bug is that the console gets spammed with lots of errors sometimes like
Error about Player Joins

**Comment by macjuul** [comment]
YAY Thanks it works!! :D

**Comment by DSH105** [comment]
Awesome :)

Could you post the entire stack trace please? :3

**Comment by macjuul** [comment]
This is one of them:

```
17.05 14:04:50 [Server] WARN Can't keep up! Did the system time change, or is the server overloaded? Running 3190ms behind, skipping 63 tick(s)
17.05 14:04:50 [Multicraft] Skipped 17 lines due to rate limit (30/s)
17.05 14:04:48 [Server] INFO at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:457) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
17.05 14:04:48 [Server] INFO at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:545) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
17.05 14:04:48 [Server] INFO at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:250) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
17.05 14:04:48 [Server] INFO at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:655) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
17.05 14:04:48 [Server] INFO at net.minecraft.server.v1_7_R1.ServerConnection.c(SourceFile:134) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
17.05 14:04:48 [Server] INFO at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:146) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
17.05 14:04:48 [Server] INFO at net.minecraft.server.v1_7_R1.PacketPlayInChat.handle(PacketPlayInChat.java:47) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
17.05 14:04:48 [Server] INFO at net.minecraft.server.v1_7_R1.PacketPlayInChat.a(PacketPlayInChat.java:28) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
17.05 14:04:48 [Server] INFO at net.minecraft.server.v1_7_R1.PlayerConnection.a(PlayerConnection.java:814) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
17.05 14:04:48 [Server] INFO at net.minecraft.server.v1_7_R1.PlayerConnection.handleCommand(PlayerConnection.java:952) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
17.05 14:04:48 [Server] INFO at org.bukkit.craftbukkit.v1_7_R1.CraftServer.dispatchCommand(CraftServer.java:683) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
17.05 14:04:48 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:175) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
17.05 14:04:48 [Server] INFO at com.dsh105.holoapi.command.DynamicPluginCommand.execute(DynamicPluginCommand.java:42) [HoloAPI.jar:?]
17.05 14:04:48 [Server] INFO at com.dsh105.holoapi.command.CommandModuleManager.onCommand(CommandModuleManager.java:95) [HoloAPI.jar:?]
17.05 14:04:48 [Server] INFO at com.dsh105.holoapi.command.module.ReloadCommand.onCommand(ReloadCommand.java:41) [HoloAPI.jar:?]
17.05 14:04:48 [Server] INFO at com.dsh105.holoapi.HoloAPICore.loadHolograms(HoloAPICore.java:227) [HoloAPI.jar:?]
17.05 14:04:48 [Server] INFO at com.dsh105.holoapi.api.SimpleHoloManager.loadFileData(SimpleHoloManager.java:299) [HoloAPI.jar:?]
17.05 14:04:48 [Server] INFO at com.dsh105.holoapi.api.SimpleHoloManager.loadExtraData(SimpleHoloManager.java:365) [HoloAPI.jar:?]
17.05 14:04:48 [Server] INFO at com.dsh105.holoapi.api.SimpleHoloManager.callDataLoadEvent(SimpleHoloManager.java:378) [HoloAPI.jar:?]
17.05 14:04:48 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:471) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
17.05 14:04:48 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:486) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
17.05 14:04:48 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
17.05 14:04:48 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
17.05 14:04:48 [Server] INFO org.bukkit.event.EventException
17.05 14:04:48 [Server] ERROR Could not pass event HoloTouchActionLoadEvent to HoloAPI v1.2.4-SNAPSHOT
```

**Comment by macjuul** [comment]
Its the only error I get now. It happens on server startup and sometimes when a player joins

**Comment by macjuul** [comment]
Another bug: When you use %item:ID% in a line the item will show up in the middle of the line and any text on the line will disapear

AND Another bug: When you use /holo editline to change a line that contains an %item% people nearby will crash

**Comment by DSH105** [comment]
Hopefully that error (stacktrace above) should now be fixed. Floating items are supposed to clear the line of a hologram as it would be far to complex to juggle both text and items on the same line together.
