### ISSUE TITLE
Big error crashing the server and spamming the console

### ISSUE THREAD

**Issue by macjuul** [DSH105/HoloAPI#84]
I got this error spammed in my console and it freezed the server

```
23.05 17:28:28 [Server] INFO at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:545) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
23.05 17:28:28 [Server] INFO at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:250) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
23.05 17:28:28 [Server] INFO at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:629) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
23.05 17:28:28 [Server] INFO at net.minecraft.server.v1_7_R1.WorldServer.doTick(WorldServer.java:192) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
23.05 17:28:28 [Server] INFO at net.minecraft.server.v1_7_R1.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:310) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
23.05 17:28:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:471) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
23.05 17:28:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:486) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
23.05 17:28:28 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
23.05 17:28:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
23.05 17:28:28 [Server] INFO org.bukkit.event.EventException
23.05 17:28:28 [Server] ERROR Could not pass event ChunkUnloadEvent to HoloAPI v1.2.4-SNAPSHOT
23.05 17:28:28 [Server] INFO Caused by: java.lang.NullPointerException
23.05 17:28:28 [Server] INFO at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
23.05 17:28:28 [Server] INFO at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:457) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
23.05 17:28:28 [Server] INFO at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:545) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
23.05 17:28:28 [Server] INFO at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:250) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
23.05 17:28:28 [Server] INFO at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:629) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
23.05 17:28:28 [Server] INFO at net.minecraft.server.v1_7_R1.WorldServer.doTick(WorldServer.java:192) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
23.05 17:28:28 [Server] INFO at net.minecraft.server.v1_7_R1.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:310) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
23.05 17:28:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:471) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
23.05 17:28:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:486) [craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
23.05 17:28:28 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
23.05 17:28:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[craftbukkit-beta-os.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
23.05 17:28:28 [Server] INFO org.bukkit.event.EventException
23.05 17:28:28 [Server] ERROR Could not pass event ChunkUnloadEvent to HoloAPI v1.2.4-SNAPSHOT
```

**Comment by DSH105** [comment]
Are you sure that's the entire stacktrace?

**Comment by drtshock** [comment]
Closing due to incomplete report.
