### ISSUE TITLE
[MCPC+ 1.7.2] Could not pass event PlayerJoinEvent to HoloAPI v.1.2.3

### ISSUE THREAD

**Issue by Rothendras** [DSH105/HoloAPI#85]
Dear,
You made a very good plugin! It works on my Mcpc+ 1.7.2 server, but when a player join it, I have a huge error in the console.

This is the error :

```
[21:12:11] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to HoloAPI v1.2.3
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:330) ~[JavaPluginLoader$1.class:git-MCPC-Plus-1.7.2-R0.4-forge1083-77]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-MCPC-Plus-1.7.2-R0.4-forge1083-77]
    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:47) ~[TimedRegisteredListener.class:git-MCPC-Plus-1.7.2-R0.4-forge1083-77]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:487) [SimplePluginManager.class:git-MCPC-Plus-1.7.2-R0.4-forge1083-77]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:472) [SimplePluginManager.class:git-MCPC-Plus-1.7.2-R0.4-forge1083-77]
    at net.minecraft.server.management.ServerConfigurationManager.func_72377_c(ServerConfigurationManager.java:316) [ld.class:?]
    at net.minecraft.server.management.ServerConfigurationManager.a(ServerConfigurationManager.java:183) [ld.class:?]
    at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:173) [NetworkDispatcher.class:git-MCPC-Plus-1.7.2-R0.4-forge1083-77]
    at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:446) [NetworkDispatcher.class:git-MCPC-Plus-1.7.2-R0.4-forge1083-77]
    at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:17) [HandshakeCompletionHandler.class:git-MCPC-Plus-1.7.2-R0.4-forge1083-77]
    at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) [HandshakeCompletionHandler.class:git-MCPC-Plus-1.7.2-R0.4-forge1083-77]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:71) [FMLProxyPacket.class:git-MCPC-Plus-1.7.2-R0.4-forge1083-77]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:206) [ef.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [ms.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:929) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:429) [lj.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:759) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_51]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/util/io/netty/channel/Channel
    at com.dsh105.holoapi.protocol.PlayerUtil.getChannel(PlayerUtil.java:59) ~[?:?]
    at com.dsh105.holoapi.protocol.netty.mcpc.MCPCChannelPipelineInjector.getChannel(MCPCChannelPipelineInjector.java:144) ~[?:?]
    at com.dsh105.holoapi.protocol.netty.mcpc.MCPCChannelPipelineInjector.<init>(MCPCChannelPipelineInjector.java:69) ~[?:?]
    at com.dsh105.holoapi.protocol.InjectionStrategy$2.inject(InjectionStrategy.java:38) ~[?:?]
    at com.dsh105.holoapi.protocol.InjectionManager.inject(InjectionManager.java:101) ~[?:?]
    at com.dsh105.holoapi.protocol.InjectionManager$1.onJoin(InjectionManager.java:74) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_51]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_51]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:328) ~[JavaPluginLoader$1.class:git-MCPC-Plus-1.7.2-R0.4-forge1083-77]
    ... 27 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.util.io.netty.channel.Channel
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:365) ~[PluginClassLoader.class:git-MCPC-Plus-1.7.2-R0.4-forge1083-77]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:212) ~[PluginClassLoader.class:git-MCPC-Plus-1.7.2-R0.4-forge1083-77]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_51]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_51]
    at com.dsh105.holoapi.protocol.PlayerUtil.getChannel(PlayerUtil.java:59) ~[?:?]
    at com.dsh105.holoapi.protocol.netty.mcpc.MCPCChannelPipelineInjector.getChannel(MCPCChannelPipelineInjector.java:144) ~[?:?]
    at com.dsh105.holoapi.protocol.netty.mcpc.MCPCChannelPipelineInjector.<init>(MCPCChannelPipelineInjector.java:69) ~[?:?]
    at com.dsh105.holoapi.protocol.InjectionStrategy$2.inject(InjectionStrategy.java:38) ~[?:?]
    at com.dsh105.holoapi.protocol.InjectionManager.inject(InjectionManager.java:101) ~[?:?]
    at com.dsh105.holoapi.protocol.InjectionManager$1.onJoin(InjectionManager.java:74) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_51]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_51]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:328) ~[JavaPluginLoader$1.class:git-MCPC-Plus-1.7.2-R0.4-forge1083-77]
    ... 27 more
```

**Comment by drtshock** [comment]
Somewhat duplicated by https://github.com/DSH105/HoloAPI/issues/61 where discussion has taken place.
