### ISSUE TITLE
Holo bugs with Cauldron-1.7.2

### ISSUE THREAD

**Issue by Melonking906** [DSH105/HoloAPI#89]
```
[17:39:35 ERROR]: Could not pass event PlayerJoinEvent to HoloAPI v1.2.3
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:330) ~[JavaPluginLoader$1.class:git-Cauldron-1.7.2-1.1112.04.1616]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cauldron-1.7.2-1.1112.04.1616]
    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30) ~[TimedRegisteredListener.class:git-Cauldron-1.7.2-1.1112.04.1616]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:487) [SimplePluginManager.class:git-Cauldron-1.7.2-1.1112.04.1616]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:472) [SimplePluginManager.class:git-Cauldron-1.7.2-1.1112.04.1616]
    at net.minecraft.server.management.ServerConfigurationManager.func_72377_c(ServerConfigurationManager.java:316) [ld.class:?]
    at net.minecraft.server.management.ServerConfigurationManager.a(ServerConfigurationManager.java:183) [ld.class:?]
    at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:173) [NetworkDispatcher.class:git-Cauldron-1.7.2-1.1112.04.1616]
    at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:448) [NetworkDispatcher.class:git-Cauldron-1.7.2-1.1112.04.1616]
    at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:17) [HandshakeCompletionHandler.class:git-Cauldron-1.7.2-1.1112.04.1616]
    at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) [HandshakeCompletionHandler.class:git-Cauldron-1.7.2-1.1112.04.1616]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:72) [FMLProxyPacket.class:git-Cauldron-1.7.2-1.1112.04.1616]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:206) [ef.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [ms.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:946) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:429) [lj.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:776) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:639) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
Caused by: java.lang.RuntimeException: Failed to find class: net.minecraft.server.v1_7_R1.NetworkManager
    at com.dsh105.holoapi.reflection.utility.ClassPackageMapper.getClass(ClassPackageMapper.java:52) ~[?:?]
    at com.dsh105.holoapi.reflection.utility.CommonReflection.getMinecraftClass(CommonReflection.java:227) ~[?:?]
    at com.dsh105.holoapi.util.ReflectionUtil.getNMSClass(ReflectionUtil.java:77) ~[?:?]
    at com.dsh105.holoapi.protocol.proxy.ProxyPlayerInjector.<init>(ProxyPlayerInjector.java:38) ~[?:?]
    at com.dsh105.holoapi.protocol.InjectionStrategy$1.inject(InjectionStrategy.java:31) ~[?:?]
    at com.dsh105.holoapi.protocol.InjectionManager.inject(InjectionManager.java:101) ~[?:?]
    at com.dsh105.holoapi.protocol.InjectionManager$1.onJoin(InjectionManager.java:74) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_05]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_05]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_05]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:328) ~[JavaPluginLoader$1.class:git-Cauldron-1.7.2-1.1112.04.1616]
    ... 27 more

=====

[17:49:28 INFO]: Melonking issued server command: /holo create
[17:49:34 ERROR]: Error handling conversation prompt
java.lang.RuntimeException: Failed to find class: net.minecraft.server.v1_7_R1.Packet
    at com.dsh105.holoapi.reflection.utility.ClassPackageMapper.getClass(ClassPackageMapper.java:52) ~[?:?]
    at com.dsh105.holoapi.reflection.utility.CommonReflection.getMinecraftClass(CommonReflection.java:227) ~[?:?]
    at com.dsh105.holoapi.util.ReflectionUtil.getNMSClass(ReflectionUtil.java:77) ~[?:?]
    at com.dsh105.holoapi.util.wrapper.protocol.Packet.<init>(Packet.java:56) ~[?:?]
    at com.dsh105.holoapi.util.wrapper.protocol.Packet.<init>(Packet.java:40) ~[?:?]
    at com.dsh105.holoapi.util.wrapper.WrapperPacketAttachEntity.<init>(WrapperPacketAttachEntity.java:27) ~[?:?]
    at com.dsh105.holoapi.api.Hologram.generate(Hologram.java:742) ~[?:?]
    at com.dsh105.holoapi.api.Hologram.show(Hologram.java:618) ~[?:?]
    at com.dsh105.holoapi.api.Hologram.show(Hologram.java:587) ~[?:?]
    at com.dsh105.holoapi.api.HologramFactory.build(HologramFactory.java:252) ~[?:?]
    at com.dsh105.holoapi.conversation.InputSuccessPrompt.getPromptText(InputSuccessPrompt.java:40) ~[?:?]
    at org.bukkit.conversations.Conversation.outputNextPrompt(Conversation.java:291) ~[Conversation.class:git-Cauldron-1.7.2-1.1112.04.1616]
    at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:230) [Conversation.class:git-Cauldron-1.7.2-1.1112.04.1616]
    at org.bukkit.craftbukkit.v1_7_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:52) [ConversationTracker.class:git-Cauldron-1.7.2-1.1112.04.1616]
    at org.bukkit.craftbukkit.v1_7_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:998) [CraftPlayer.class:git-Cauldron-1.7.2-1.1112.04.1616]
    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1140) [mx.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ie.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ie.class:?]
    at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:99) [ef.class:?]
    at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:310) [ef.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at cpw.mods.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:193) [NetworkDispatcher.class:git-Cauldron-1.7.2-1.1112.04.1616]
    at cpw.mods.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:43) [NetworkDispatcher.class:git-Cauldron-1.7.2-1.1112.04.1616]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) [ByteToMessageDecoder.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) [ByteToMessageDecoder.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149) [ReadTimeoutHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100) [AbstractNioByteChannel$NioByteUnsafe.class:?]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
```

**Comment by CaptainBern** [comment]
I exactly know how to fix this, and why it is there in the first place but we're in a major rewrite now, which will fix all issues. Builds for Cauldron/MCPC+ will most likely be released as a seperate plugin since they do some stuff we can't fix.
