### ISSUE TITLE
Extremely low ticks and disappearing holograms on v2.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by Melonking906** [DSH105/HoloAPI#99]
Holograms often vanish just after loading, low tick rate, and this error.

```
[00:00:30] [Server thread/ERROR]: Could not pass event ChunkLoadEvent to HoloAPI v2.0.0-SNAPSHOT
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[spigot.jar:git-Spigot-1564]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1564]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1564]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1564]
    at org.bukkit.craftbukkit.v1_7_R4.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:50) [spigot.jar:git-Spigot-1564]
    at org.bukkit.craftbukkit.v1_7_R4.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:13) [spigot.jar:git-Spigot-1564]
    at org.bukkit.craftbukkit.v1_7_R4.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) [spigot.jar:git-Spigot-1564]
    at org.bukkit.craftbukkit.v1_7_R4.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) [spigot.jar:git-Spigot-1564]
    at org.bukkit.craftbukkit.v1_7_R4.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) [spigot.jar:git-Spigot-1564]
    at net.minecraft.server.v1_7_R4.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) [spigot.jar:git-Spigot-1564]
    at net.minecraft.server.v1_7_R4.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:102) [spigot.jar:git-Spigot-1564]
    at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.getChunkAt(CraftWorld.java:121) [spigot.jar:git-Spigot-1564]
    at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.getChunkAt(CraftWorld.java:539) [spigot.jar:git-Spigot-1564]
    at org.bukkit.Location.getChunk(Location.java:73) [spigot.jar:git-Spigot-1564]
    at com.dsh105.holoapi.listeners.HoloListener.onChunkLoad(HoloListener.java:114) [HoloAPI.jar:?]
    at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_55]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_55]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) [spigot.jar:git-Spigot-1564]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-1564]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1564]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1564]
    at org.bukkit.craftbukkit.v1_7_R4.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:50) [spigot.jar:git-Spigot-1564]
    at org.bukkit.craftbukkit.v1_7_R4.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:13) [spigot.jar:git-Spigot-1564]
    at org.bukkit.craftbukkit.v1_7_R4.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) [spigot.jar:git-Spigot-1564]
    at org.bukkit.craftbukkit.v1_7_R4.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) [spigot.jar:git-Spigot-1564]
    at org.bukkit.craftbukkit.v1_7_R4.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) [spigot.jar:git-Spigot-1564]
    at net.minecraft.server.v1_7_R4.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) [spigot.jar:git-Spigot-1564]
    at net.minecraft.server.v1_7_R4.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:102) [spigot.jar:git-Spigot-1564]
    at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.getChunkAt(CraftWorld.java:121) [spigot.jar:git-Spigot-1564]
    at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.getBlockAt(CraftWorld.java:85) [spigot.jar:git-Spigot-1564]
    at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:222) [spigot.jar:git-Spigot-1564]
    at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:212) [spigot.jar:git-Spigot-1564]
    at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1055) [spigot.jar:git-Spigot-1564]
    at net.minecraft.server.v1_7_R4.PacketPlayInArmAnimation.a(SourceFile:43) [spigot.jar:git-Spigot-1564]
    at net.minecraft.server.v1_7_R4.PacketPlayInArmAnimation.handle(SourceFile:9) [spigot.jar:git-Spigot-1564]
    at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1564]
    at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1564]
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:731) [spigot.jar:git-Spigot-1564]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1564]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1564]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1564]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1564]
Caused by: java.util.NoSuchElementException: packet_handler
    at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:905) ~[spigot.jar:git-Spigot-1564]
    at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:160) ~[spigot.jar:git-Spigot-1564]
    at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:153) ~[spigot.jar:git-Spigot-1564]
    at com.dsh105.holoapi.protocol.netty.PlayerInjector.inject(PlayerInjector.java:74) ~[?:?]
    at com.dsh105.holoapi.protocol.InjectionManager.inject(InjectionManager.java:98) ~[?:?]
    at com.dsh105.holoapi.protocol.InjectionManager.getInjectorFor(InjectionManager.java:75) ~[?:?]
    at com.dsh105.holoapi.api.HologramImpl.generate(HologramImpl.java:647) ~[?:?]
    at com.dsh105.holoapi.api.HologramImpl.show(HologramImpl.java:462) ~[?:?]
    at com.dsh105.holoapi.api.HologramImpl.show(HologramImpl.java:438) ~[?:?]
    at com.dsh105.holoapi.listeners.HoloListener.onChunkLoad(HoloListener.java:118) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_55]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_55]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[spigot.jar:git-Spigot-1564]
    ... 42 more
```

**Comment by DSH105** [comment]
Can you provide a timings report to accompany your ticket? :)

**Comment by Melonking906** [comment]
Drop from the normal 19.6tps or so to 11tps

**Comment by DSH105** [comment]
I need the actual report so I can see where the problem might be :3

**Comment by Melonking906** [comment]
[11:04:03] [Server thread/INFO]: DO NOT CHANGE A WORLD'S TIME OR PERFORM A HEAVY OPERATION.
[11:04:24] [Server thread/INFO]: Warning: Bukkit scheduler inaccurate; expected 100, got 99
[11:04:24] [Server thread/INFO]: Clock test result: CLOCK BEHIND
[11:04:24] [Server thread/INFO]: WARNING: You have potential block respawn issues.
[11:04:24] [Server thread/INFO]: Expected time elapsed: 5000.0ms
[11:04:24] [Server thread/INFO]: Time elapsed: 21039ms
[11:04:24] [Server thread/INFO]: Error: -76.23461191121251%
[11:04:24] [Server thread/INFO]: Actual clock rate: 4.705546841579923 ticks/sec
[11:04:24] [Server thread/INFO]: Expected clock rate: 20 ticks/sec

**Comment by Melonking906** [comment]
I assume you meant this actually, http://pastebin.com/P60Qfe2Q

**Comment by DSH105** [comment]
Yep, that's the one. I'll see what I can do.

**Comment by DSH105** [comment]
Could I have a look at your hologram data file too?

**Comment by Melonking906** [comment]
Here ye go http://pastebin.com/N8HQJA8c

**Comment by CaptainBern** [comment]
Seems like a spigot only issue. I guess it is caused by our packet listening system which apperantly is not compatible with Spigot anymore. I will see what I can do ;)

**Comment by Melonking906** [comment]
Thank you, the server seems a little be emptier without them.
